job_type == 7
is_continue == false
Metadata label for images: == rlnImageName
Sigma-value for discarding images: == 4
OR: select on image statistics? == No
Submit to queue? == No
Randomise order before making subsets?: == No
Re-center the class averages? == Yes
Regroup the particles? == No
OR: remove duplicates? == No
Select based on metadata values? == No
OR: split into subsets? == Yes
Minimum inter-particle distance (A) == 30
OR select from picked coords: == 
OR select from particles.star: == Schedules/preprocess/extract_refpick/particles.star
OR select from micrographs.star: == 
Select classes from model.star: == 
Pixel size before extraction (A) == -1
Minimum dedicated cores per node: == 24
Approximate nr of groups:  == 1
OR: number of subsets:  == -1
Additional arguments: == 
Queue submit command: == qsub
Standard submission script: == /public/EM/RELION/relion/bin/relion_qsub.csh
Queue name:  == openmpi
Metadata label for subset selection: == rlnCtfFigureOfMerit
Maximum metadata value: == 9999.
Minimum metadata value: == -9999.
Subset size:  == $$subset_size
